Script started on 2016年03月06日 (週日) 22時45分02秒
]0;F74046365@2015cpp: ~/lab1F74046365@2015cpp:~/lab1$ whoami; pwd
F74046365
/home/F74046365/lab1
]0;F74046365@2015cpp: ~/lab1F74046365@2015cpp:~/lab1$  gitconfig-l -l[1@ 
user.name=stbn199650
user.email=stbn199650@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/stbn199650/lab1.git
branch.master.remote=origin
branch.master.merge=refs/heads/master
remote.A1.url=https://github.com/stbn199650/lab1.git
remote.A1.fetch=+refs/heads/*:refs/remotes/A1/*
]0;F74046365@2015cpp: ~/lab1F74046365@2015cpp:~/lab1$  gitclonehttps://github.com/<your githubaccount>/lab1.g it[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C/lab1.git[K[A]0;F74046365@2015cpp: ~/lab1F74046365@2015cpp:~/lab1$ [C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C/lab1.git [K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1P/lab1.git
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gits/lab1.gitt/lab1.gitb/lab1.gitn/lab1.git1/lab1.git9/lab1.git9/lab1.git6/lab1.git5/lab1.git0/lab1.git[C https://github.com/stbn199650/lab1.git[1@ 
Cloning into 'lab1'...
remote: Counting objects: 15, done.[K
remote: Compressing objects:   7% (1/14)   [Kremote: Compressing objects:  14% (2/14)   [Kremote: Compressing objects:  21% (3/14)   [Kremote: Compressing objects:  28% (4/14)   [Kremote: Compressing objects:  35% (5/14)   [Kremote: Compressing objects:  42% (6/14)   [Kremote: Compressing objects:  50% (7/14)   [Kremote: Compressing objects:  57% (8/14)   [Kremote: Compressing objects:  64% (9/14)   [Kremote: Compressing objects:  71% (10/14)   [Kremote: Compressing objects:  78% (11/14)   [Kremote: Compressing objects:  85% (12/14)   [Kremote: Compressing objects:  92% (13/14)   [Kremote: Compressing objects: 100% (14/14)   [Kremote: Compressing objects: 100% (14/14), done.[K
remote: Total 15 (delta 4), reused 11 (delta 1), pack-reused 0[K
Unpacking objects:   6% (1/15)   Unpacking objects:  13% (2/15)   Unpacking objects:  20% (3/15)   Unpacking objects:  26% (4/15)   Unpacking objects:  33% (5/15)   Unpacking objects:  40% (6/15)   Unpacking objects:  46% (7/15)   Unpacking objects:  53% (8/15)   Unpacking objects:  60% (9/15)   Unpacking objects:  66% (10/15)   Unpacking objects:  73% (11/15)   Unpacking objects:  80% (12/15)   Unpacking objects:  86% (13/15)   Unpacking objects:  93% (14/15)   Unpacking objects: 100% (15/15)   Unpacking objects: 100% (15/15), done.
]0;F74046365@2015cpp: ~/lab1F74046365@2015cpp:~/lab1$ cat lab1.script
]0;F74046365@2015cpp: ~/lab1F74046365@2015cpp:~/lab1$ exit

Script done on 2016年03月06日 (週日) 22時46分16秒
